import { Platform, StyleSheet } from 'react-native';
import {
  background,
  border,
  borderRadius,
  fontSize,
  fontWeight,
  lineHeight,
  primary,
  shadows,
  spacing,
  status,
  surface,
  text,
} from '../theme';

const HEADER_HEIGHT = Platform.OS === 'ios'
  ? spacing['4xl'] - spacing.xs
  : spacing['4xl'] + spacing.sm;
const ICON_TOUCH_SIZE = spacing['4xl'] - spacing.xs;
const HEADER_SIDE_WIDTH = ICON_TOUCH_SIZE * 2;

function withOpacity(hexColor, opacity) {
  const hex = hexColor.replace('#', '');
  const value = hex.length === 3
    ? hex.split('').map((char) => char + char).join('')
    : hex;
  const intValue = parseInt(value, 16);
  const r = (intValue >> 16) & 255;
  const g = (intValue >> 8) & 255;
  const b = intValue & 255;
  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: background.secondary,
  },
  headerBar: {
    height: 74,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginHorizontal: 9,
    marginTop: Platform.OS === 'ios' ? 8 : 16,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: 'rgba(99, 94, 94, 0.19)',
    position: 'relative',
  },
  headerSide: {
    width: HEADER_SIDE_WIDTH,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRightSide: {
    justifyContent: 'flex-end',
  },
  headerIconButton: {
    width: ICON_TOUCH_SIZE,
    height: ICON_TOUCH_SIZE,
    borderRadius: ICON_TOUCH_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    position: 'absolute',
    left: 0,
    right: 0,
    textAlign: 'center',
    color: text.primary,
    fontSize: fontSize.title,
    lineHeight: lineHeight.title,
    fontWeight: fontWeight.bold,
  },
  notificationIconWrap: {
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: 2,
    right: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: status.danger,
  },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  listContent: {
    paddingBottom:150,
  },
  profileCard: {
    marginHorizontal: spacing.base,
    marginTop: spacing.base,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    backgroundColor: background.primary,
    borderRadius: borderRadius.base,
    alignItems: 'center',
    ...shadows.sm,
  },
  profileAvatarFrame: {
    position: 'relative',
    marginBottom: spacing.md,
  },
  cameraBadge: {
    position: 'absolute',
    right: -spacing.xs,
    bottom: spacing.xs,
    width: spacing['2xl'],
    height: spacing['2xl'],
    borderRadius: spacing.base,
    backgroundColor: primary.DEFAULT,
    borderWidth: 2,
    borderColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileName: {
    maxWidth: '100%',
    color: text.primary,
    fontSize: fontSize.heading,
    lineHeight: lineHeight.heading,
    fontWeight: fontWeight.bold,
    textAlign: 'center',
  },
  profileBio: {
    marginTop: spacing.sm,
    color: surface.muted,
    fontSize: fontSize.body,
    lineHeight: lineHeight.heading,
    textAlign: 'center',
  },
  activePill: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.lg,
    backgroundColor: withOpacity(status.success, 0.18),
  },
  activeText: {
    color: status.successDark,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.caption,
    fontWeight: fontWeight.bold,
  },
  statsCard2x2: {
    marginHorizontal: spacing.base,
    marginTop: spacing.md,
    backgroundColor: background.primary,
    borderRadius: borderRadius.base,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    paddingVertical: spacing.sm,
    ...shadows.sm,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statCell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
  },
  statVerticalDivider: {
    width: 1,
    height: spacing['3xl'],
    backgroundColor: '#EAEAEA',
  },
  statHorizontalDivider: {
    height: 1,
    marginHorizontal: spacing.base,
    backgroundColor: '#EAEAEA',
  },
  statValue: {
    color: text.primary,
    fontSize: fontSize.heading,
    lineHeight: lineHeight.heading,
    fontWeight: fontWeight.bold,
  },
  statLabel: {
    marginTop: spacing.xs,
    color: text.hint,
    fontSize: fontSize.caption2,
    lineHeight: lineHeight.caption,
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
  },
  infoSection: {
    marginHorizontal: spacing.base,
    marginTop: spacing.md,
  },
  infoRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.base,
    marginBottom: spacing.sm,
    backgroundColor: background.primary,
    borderRadius: borderRadius.base,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    ...shadows.sm,
  },
  infoIconWrap: {
    width: spacing['4xl'],
    height: spacing['4xl'],
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: primary.DEFAULT,
    backgroundColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoTextBlock: {
    flex: 1,
    marginLeft: spacing.md,
  },
  infoLabel: {
    color: text.hint,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.caption,
    fontWeight: fontWeight.medium,
  },
  infoValue: {
    marginTop: spacing.xs,
    color: text.primary,
    fontSize: fontSize.bodyLarge,
    lineHeight: lineHeight.bodyLarge,
    fontWeight: fontWeight.bold,
  },
  managementCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: spacing.base,
    marginTop: spacing.md,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.md,
    backgroundColor: background.primary,
    borderRadius: borderRadius.base,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    ...shadows.sm,
  },
  managementCardLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  managementCardIconWrap: {
    width: spacing['4xl'],
    height: spacing['4xl'],
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: primary.DEFAULT,
    backgroundColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managementCardTextBlock: {
    flex: 1,
    marginLeft: spacing.md,
  },
  managementCardTitle: {
    color: text.primary,
    fontSize: fontSize.bodyLarge,
    lineHeight: lineHeight.bodyLarge,
    fontWeight: fontWeight.bold,
  },
  managementCardSubtitle: {
    marginTop: spacing.xs,
    color: text.hint,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.caption,
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: withOpacity(text.primary, 0.42),
  },
  sheetContainer: {
    backgroundColor: background.primary,
    borderTopLeftRadius: borderRadius['2xl'],
    borderTopRightRadius: borderRadius['2xl'],
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: Platform.OS === 'ios' ? spacing['2xl'] : spacing.lg,
  },
  sheetHandle: {
    width: spacing['3xl'],
    height: spacing.xs,
    borderRadius: borderRadius.xs,
    backgroundColor: withOpacity(border.default, 0.45),
    alignSelf: 'center',
    marginBottom: spacing.base,
  },
  sheetTitle: {
    marginBottom: spacing.md,
    color: text.primary,
    fontSize: fontSize.title,
    lineHeight: lineHeight.title,
    fontWeight: fontWeight.bold,
    textAlign: 'center',
  },
  sheetOption: {
    minHeight: spacing['5xl'],
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  sheetOptionText: {
    color: text.primary,
    fontSize: fontSize.subtitle,
    lineHeight: lineHeight.subtitle,
    fontWeight: fontWeight.medium,
  },
  sheetOptionTextDanger: {
    color: status.danger,
  },
  sheetDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: withOpacity(border.default, 0.32),
  },
  editOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: withOpacity(text.primary, 0.42),
  },
  editSheet: {
    maxHeight: '86%',
    backgroundColor: background.primary,
    borderTopLeftRadius: borderRadius['2xl'],
    borderTopRightRadius: borderRadius['2xl'],
    paddingBottom: Platform.OS === 'ios' ? spacing['2xl'] : spacing.lg,
  },
  editHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.base,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: withOpacity(border.default, 0.32),
  },
  editTitle: {
    color: text.primary,
    fontSize: fontSize.title,
    lineHeight: lineHeight.title,
    fontWeight: fontWeight.bold,
  },
  editBody: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.base,
  },
  inputLabel: {
    marginTop: spacing.base,
    marginBottom: spacing.sm,
    color: surface.muted,
    fontSize: fontSize.bodySmall,
    lineHeight: lineHeight.bodySmall,
    fontWeight: fontWeight.bold,
  },
  modalInput: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withOpacity(border.default, 0.48),
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.md,
    color: text.primary,
    backgroundColor: background.primary,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
  },
  modalInputDisabled: {
    backgroundColor: background.secondary,
    color: text.disabled,
  },
  modalTextarea: {
    minHeight: spacing['5xl'] + spacing.base,
    textAlignVertical: 'top',
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  optionCard: {
    minWidth: '30%',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withOpacity(border.default, 0.48),
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    backgroundColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  positionCard: {
    minWidth: '31%',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withOpacity(border.default, 0.48),
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    backgroundColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionCardActive: {
    borderColor: primary.DEFAULT,
    backgroundColor: withOpacity(primary.DEFAULT, 0.1),
  },
  optionText: {
    color: text.primary,
    fontSize: fontSize.bodySmall,
    lineHeight: lineHeight.bodySmall,
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
  },
  optionTextActive: {
    color: primary.DEFAULT,
    fontWeight: fontWeight.bold,
  },
  editFooter: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.base,
  },
  cancelButton: {
    flex: 1,
    minHeight: spacing['4xl'],
    borderRadius: borderRadius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withOpacity(border.default, 0.48),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: surface.muted,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    fontWeight: fontWeight.semibold,
  },
  saveButton: {
    flex: 1,
    minHeight: spacing['4xl'],
    borderRadius: borderRadius.md,
    backgroundColor: primary.DEFAULT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: background.primary,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    fontWeight: fontWeight.bold,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    backgroundColor: withOpacity(background.primary, 0.78),
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingOverlayText: {
    marginTop: spacing.md,
    color: primary.DEFAULT,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    fontWeight: fontWeight.semibold,
  },
});