import { Platform, StyleSheet } from 'react-native';
import {
  background,
  border,
  borderRadius,
  fontSize,
  fontWeight,
  lineHeight,
  primary,
  shadows,
  spacing,
  status,
  surface,
  text,
} from '../theme';

const HEADER_HEIGHT = Platform.OS === 'ios'
  ? spacing['4xl'] - spacing.xs
  : spacing['4xl'] + spacing.sm;
const ICON_TOUCH_SIZE = spacing['4xl'] - spacing.xs;
const HEADER_SIDE_WIDTH = ICON_TOUCH_SIZE * 2;

function withOpacity(hexColor, opacity) {
  const hex = hexColor.replace('#', '');
  const value = hex.length === 3
    ? hex.split('').map((char) => char + char).join('')
    : hex;
  const intValue = parseInt(value, 16);
  const r = (intValue >> 16) & 255;
  const g = (intValue >> 8) & 255;
  const b = intValue & 255;
  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F5F5F7',
  },
  headerBar: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EAEAEA',
    position: 'relative',
  },
  headerSide: {
    width: HEADER_SIDE_WIDTH,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRightSide: {
    justifyContent: 'flex-end',
  },
  headerIconButton: {
    width: ICON_TOUCH_SIZE,
    height: ICON_TOUCH_SIZE,
    borderRadius: ICON_TOUCH_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    position: 'absolute',
    left: 0,
    right: 0,
    textAlign: 'center',
    color: text.primary,
    fontSize: fontSize.title,
    lineHeight: lineHeight.title,
    fontWeight: fontWeight.bold,
  },
  notificationIconWrap: {
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: 2,
    right: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: status.danger,
  },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  listContent: {
    paddingBottom:150,
  },
  profileCard: {
    marginHorizontal: spacing.base,
    marginTop: spacing.base,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    backgroundColor: background.primary,
    borderRadius: borderRadius.base,
    alignItems: 'center',
    ...shadows.sm,
  },
  profileCardLeftLayout: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
    backgroundColor: '#FFFFFF',
  },
  profileTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  avatarColumnContainer: {
    alignItems: 'center',
    marginRight: 12,
  },
  avatarStatusWrap: {
    position: 'relative',
    padding: 1.5,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  avatarRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 4,
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    backgroundColor: '#FEF3C7',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  avatarRatingText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#D97706',
  },
  onlineDotBadge: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#22C55E',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  offlinePillBadge: {
    position: 'absolute',
    right: -6,
    bottom: -2,
    backgroundColor: '#374151',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  offlinePillText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#86EFAC',
  },
  profileRightContent: {
    flex: 1,
    height: 60,
    justifyContent: 'center',
    paddingLeft: 2,
    marginTop: 5,
  },
  profileNameLeft: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
    textAlign: 'left',
  },
  statsInlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statInlineItem: {
    alignItems: 'flex-start',
    flex: 1,
    paddingRight: 2,
  },
  statInlineValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'left',
  },
  statInlineLabel: {
    fontSize: 10.5,
    fontWeight: '400',
    color: '#6B7280',
    marginTop: 1,
    textAlign: 'left',
  },
  statusTextSmall: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '500',
  },
  profileBioBottom: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    fontSize: 14,
    lineHeight: 20,
    color: '#4B5563',
  },
  avatarEditCenter: {
    alignItems: 'center',
    marginBottom: 16,
  },
  avatarEditTouch: {
    position: 'relative',
  },
  avatarEditOverlay: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: primary.DEFAULT,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  changeAvatarBtnText: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '600',
    color: primary.DEFAULT,
  },
  profileAvatarFrame: {
    position: 'relative',
    marginBottom: spacing.md,
  },
  cameraBadge: {
    position: 'absolute',
    right: -spacing.xs,
    bottom: spacing.xs,
    width: spacing['2xl'],
    height: spacing['2xl'],
    borderRadius: spacing.base,
    backgroundColor: primary.DEFAULT,
    borderWidth: 2,
    borderColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileName: {
    maxWidth: '100%',
    color: text.primary,
    fontSize: fontSize.heading,
    lineHeight: lineHeight.heading,
    fontWeight: fontWeight.bold,
    textAlign: 'center',
  },
  profileBio: {
    marginTop: spacing.sm,
    color: surface.muted,
    fontSize: fontSize.body,
    lineHeight: lineHeight.heading,
    textAlign: 'center',
  },
  activePill: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.lg,
    backgroundColor: withOpacity(status.success, 0.18),
  },
  activeText: {
    color: status.successDark,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.caption,
    fontWeight: fontWeight.bold,
  },
  statsCard2x2: {
    marginHorizontal: spacing.base,
    marginTop: spacing.md,
    backgroundColor: background.primary,
    borderRadius: borderRadius.base,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    paddingVertical: spacing.sm,
    ...shadows.sm,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statCell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
  },
  statVerticalDivider: {
    width: 1,
    height: spacing['3xl'],
    backgroundColor: '#EAEAEA',
  },
  statHorizontalDivider: {
    height: 1,
    marginHorizontal: spacing.base,
    backgroundColor: '#EAEAEA',
  },
  statValue: {
    color: text.primary,
    fontSize: fontSize.heading,
    lineHeight: lineHeight.heading,
    fontWeight: fontWeight.bold,
  },
  statLabel: {
    marginTop: spacing.xs,
    color: text.hint,
    fontSize: fontSize.caption2,
    lineHeight: lineHeight.caption,
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
  },
  infoSection: {
    marginHorizontal: spacing.base,
    marginTop: spacing.md,
  },
  infoRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.base,
    marginBottom: spacing.sm,
    backgroundColor: background.primary,
    borderRadius: borderRadius.base,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    ...shadows.sm,
  },
  infoIconWrap: {
    width: spacing['4xl'],
    height: spacing['4xl'],
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: primary.DEFAULT,
    backgroundColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoTextBlock: {
    flex: 1,
    marginLeft: spacing.md,
  },
  infoLabel: {
    color: text.hint,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.caption,
    fontWeight: fontWeight.medium,
  },
  infoValue: {
    marginTop: spacing.xs,
    color: text.primary,
    fontSize: fontSize.bodyLarge,
    lineHeight: lineHeight.bodyLarge,
    fontWeight: fontWeight.bold,
  },
  managementCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: spacing.base,
    marginTop: spacing.md,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.md,
    backgroundColor: background.primary,
    borderRadius: borderRadius.base,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    ...shadows.sm,
  },
  managementCardLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  managementCardIconWrap: {
    width: spacing['4xl'],
    height: spacing['4xl'],
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: primary.DEFAULT,
    backgroundColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managementCardTextBlock: {
    flex: 1,
    marginLeft: spacing.md,
  },
  managementCardTitle: {
    color: text.primary,
    fontSize: fontSize.bodyLarge,
    lineHeight: lineHeight.bodyLarge,
    fontWeight: fontWeight.bold,
  },
  managementCardSubtitle: {
    marginTop: spacing.xs,
    color: text.hint,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.caption,
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: withOpacity(text.primary, 0.42),
  },
  sheetContainer: {
    backgroundColor: background.primary,
    borderTopLeftRadius: borderRadius['2xl'],
    borderTopRightRadius: borderRadius['2xl'],
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: Platform.OS === 'ios' ? spacing['2xl'] : spacing.lg,
  },
  sheetHandle: {
    width: spacing['3xl'],
    height: spacing.xs,
    borderRadius: borderRadius.xs,
    backgroundColor: withOpacity(border.default, 0.45),
    alignSelf: 'center',
    marginBottom: spacing.base,
  },
  sheetTitle: {
    marginBottom: spacing.md,
    color: text.primary,
    fontSize: fontSize.title,
    lineHeight: lineHeight.title,
    fontWeight: fontWeight.bold,
    textAlign: 'center',
  },
  sheetOption: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: spacing.sm,
    paddingRight: spacing.xl,
  },
  sheetOptionText: {
    color: text.primary,
    fontSize: fontSize.subtitle,
    lineHeight: lineHeight.subtitle,
    fontWeight: fontWeight.medium,
  },
  sheetOptionTextDanger: {
    color: status.danger,
  },
  sheetDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: withOpacity(border.default, 0.32),
  },
  editOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: withOpacity(text.primary, 0.42),
  },
  editSheet: {
    maxHeight: '86%',
    backgroundColor: background.primary,
    borderTopLeftRadius: borderRadius['2xl'],
    borderTopRightRadius: borderRadius['2xl'],
    paddingBottom: Platform.OS === 'ios' ? spacing['2xl'] : spacing.lg,
  },
  editHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.base,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: withOpacity(border.default, 0.32),
  },
  editTitle: {
    color: text.primary,
    fontSize: fontSize.title,
    lineHeight: lineHeight.title,
    fontWeight: fontWeight.bold,
  },
  editBody: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.base,
  },
  inputLabel: {
    marginTop: spacing.base,
    marginBottom: spacing.sm,
    color: surface.muted,
    fontSize: fontSize.bodySmall,
    lineHeight: lineHeight.bodySmall,
    fontWeight: fontWeight.bold,
  },
  modalInput: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withOpacity(border.default, 0.48),
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.md,
    color: text.primary,
    backgroundColor: background.primary,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
  },
  modalInputDisabled: {
    backgroundColor: background.secondary,
    color: text.disabled,
  },
  modalTextarea: {
    minHeight: spacing['5xl'] + spacing.base,
    textAlignVertical: 'top',
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  optionCard: {
    minWidth: '30%',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withOpacity(border.default, 0.48),
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    backgroundColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  positionCard: {
    minWidth: '31%',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withOpacity(border.default, 0.48),
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    backgroundColor: background.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionCardActive: {
    borderColor: primary.DEFAULT,
    backgroundColor: withOpacity(primary.DEFAULT, 0.1),
  },
  optionText: {
    color: text.primary,
    fontSize: fontSize.bodySmall,
    lineHeight: lineHeight.bodySmall,
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
  },
  optionTextActive: {
    color: primary.DEFAULT,
    fontWeight: fontWeight.bold,
  },
  editFooter: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.base,
  },
  cancelButton: {
    flex: 1,
    minHeight: spacing['4xl'],
    borderRadius: borderRadius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withOpacity(border.default, 0.48),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: surface.muted,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    fontWeight: fontWeight.semibold,
  },
  saveButton: {
    flex: 1,
    minHeight: spacing['4xl'],
    borderRadius: borderRadius.md,
    backgroundColor: primary.DEFAULT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: background.primary,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    fontWeight: fontWeight.bold,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    backgroundColor: withOpacity(background.primary, 0.78),
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingOverlayText: {
    marginTop: spacing.md,
    color: primary.DEFAULT,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    fontWeight: fontWeight.semibold,
  },
  profileInfoCardBox: {
    marginHorizontal: 12,
    marginTop: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    overflow: 'hidden',
    ...shadows.sm,
  },
  tabContentCardBox: {
    marginBottom: 24,
  },
  stickyTabBarWrap: {
    backgroundColor: '#F5F5F7',
    paddingBottom: 4,
    zIndex: 10,
  },
  tabBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginHorizontal: 12,
    marginTop: 8,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  tabItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 6,
    borderRadius: 10,
    marginHorizontal: 2,
  },
  tabItemActive: {
    backgroundColor: '#FFF5F2',
  },
  tabLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
  },
  tabLabelActive: {
    color: primary.DEFAULT,
    fontWeight: '700',
  },
  inlinePostCard: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  inlinePostText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#1F2937',
    fontWeight: '500',
  },
  inlinePostMedia: {
    width: '100%',
    height: 160,
    borderRadius: 8,
    marginTop: 10,
  },
  inlinePostMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  inlinePostTime: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  inlinePostStats: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inlinePostStatCount: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4B5563',
    marginLeft: 4,
  },
  inlineMatchCard: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  inlineMatchTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  inlineMatchTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
    flex: 1,
    marginRight: 8,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
  },
  inlineMatchSub: {
    fontSize: 13,
    color: '#4B5563',
    marginBottom: 4,
  },
  inlineMatchTime: {
    fontSize: 12,
    color: '#6B7280',
  },
  emptyTabBox: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginHorizontal: 12,
    marginTop: 10,
    paddingVertical: 36,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  emptyTabTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#374151',
    marginTop: 12,
  },
  emptyTabSub: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
  },
  emptyTabBtn: {
    marginTop: 16,
    backgroundColor: primary.DEFAULT,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
  },
  emptyTabBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  postCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginHorizontal: 12,
    marginTop: 10,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  postAuthorBlock: {
    flex: 1,
    marginLeft: 10,
  },
  postAuthorName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  postTime: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  postMenuButton: {
    padding: 4,
  },
  postContent: {
    fontSize: 14,
    lineHeight: 21,
    color: '#1F2937',
    marginBottom: 10,
  },
  postImagesWrap: {
    marginTop: 6,
    marginBottom: 10,
    borderRadius: 12,
    overflow: 'hidden',
  },
  postDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 10,
  },
  postActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: 4,
  },
  postActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  postActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
  },
});
